FROM node:alpine

#----NPM installer dependency Fix:
#RUN apk update && apk upgrade && apk add --no-cache bash openssh
#RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev

RUN mkdir -p /app
WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "start"]